-- H2 schema for Favourite Places (local profile; matches JPA entities, ddl-auto=validate)

CREATE TABLE users (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    username VARCHAR(100) NOT NULL,
    password VARCHAR(100) NOT NULL,
    CONSTRAINT uq_users_username UNIQUE (username)
);

CREATE TABLE places (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(200) NOT NULL,
    address VARCHAR(500) NOT NULL,
    latitude DOUBLE NOT NULL,
    longitude DOUBLE NOT NULL,
    google_place_id VARCHAR(300) NULL,
    favourite BOOLEAN NOT NULL,
    created_at TIMESTAMP NOT NULL,
    user_id BIGINT NOT NULL,
    CONSTRAINT fk_places_user FOREIGN KEY (user_id) REFERENCES users (id),
    CONSTRAINT uq_places_user_google_place UNIQUE (user_id, google_place_id)
);

CREATE INDEX idx_places_google_place_id ON places (google_place_id);
CREATE INDEX idx_places_created_at ON places (created_at);
CREATE INDEX idx_places_user_id ON places (user_id);
